```{r load-pkgs}
# Do not change the order of the first two chunks
library(tidyverse)
library(RColorBrewer)
library(gt)
library(ggtext)
#library(plotly)
#library(countdown)
```
```{r setup-options}
knitr::opts_chunk$set(
  echo       = TRUE,
  eval       = TRUE,
  warning    = FALSE,
  message    = FALSE,
  tidy       = TRUE,
  size       = 'normalsize',
  background = '#F7F7F7',
  comment    = '##',
  dev        ='svg',
  dev.args   = list(bg = 'transparent'),
  cache      = TRUE,
  cache.path ='cache/',
  cache.vars = NULL,
  cache.lazy = TRUE,
  fig.path   ='figure/',
  fig.align  ='center',
  fig.show   ='hold',
  fig.retina = 2
)
# options(crayon.enabled = TRUE)


invthm <- theme_minimal() +
  theme(
    panel.background  = element_rect(fill = 'transparent', colour = NA),
    plot.background   = element_rect(fill = 'transparent', colour = NA),
    legend.background = element_rect(fill = 'transparent', colour = NA),
    legend.key        = element_rect(fill = 'transparent', colour = NA),
    axis.title        = element_text(size = 24),
    axis.text         = element_text(size = 18),
    strip.text        = element_text(size = 20),
    legend.title = element_text(size = 20),
    legend.text = element_text(size = 18)
  )

whitethm <- theme(
  axis.title = element_text(color="white"),
  axis.text = element_text(color="white"),
  legend.title = element_text(color="white"),
  legend.text = element_text(color="white"),
  strip.text = element_text(color="white")
)

voidthm <- theme_void() + 
  theme(
    panel.background  = element_rect(fill = 'transparent', colour = NA),
    plot.background   = element_rect(fill = 'transparent', colour = NA),
    legend.background = element_rect(fill = 'transparent', colour = NA),
    legend.key        = element_rect(fill = 'transparent', colour = NA),
    strip.text        = element_text(size = 20),
    plot.title = element_text(size=28, face="bold")
  )

theme_set(invthm)
```
